### ISSUE TITLE
vTorrent wallet not syncing

### ISSUE THREAD

**Issue by joonsup** [vtorrent/vTorrent-Client#2] opened 2017-07-01 03:59 UTC
Hasn't synced up in over a week.  Don't want to move tokens into wallet until i can sync it.  What's wrong

**Comment by Jousepetion** [comment] 2017-09-26 02:57
hi, having the same issue, but unlike you, like an idiot, I sent a deposit. Was this issue ever resolved for you?

**Comment by g1itch** [comment] 2017-09-28 15:08
Use addnode, dude.

**Comment by Jousepetion** [comment] 2017-09-28 15:15
I've been using the info from https://bitcointalk.org/index.php?topic=889481.2760 to add the code...no luck do you have another source I can use?

**Comment by g1itch** [comment] 2017-09-28 15:20
Use block explorer: http://vtrchains.com/network

**Comment by Jousepetion** [comment] 2017-09-28 15:23
Thanks, I've done this as well. Is there coding I need to past as well.

**Comment by joonsup** [comment] 2017-09-28 15:28
Sorry I gave up and kept those tokens on the exchange.  Haven't looked into it for a couple month but seems like there's still a wallet issue.

**Comment by jhmblvd** [comment] 2017-11-10 16:59
Boy getting a wallet right and working seems to me to be a priority. I purchased vTorrent tokens then blithely transferred them to my wallet only to have them never show up. The wallet says Out of Sync and nothing I've done helps. Have I lost the coin?

**Comment by joonsup** [comment] 2017-11-10 17:22
Sorry to hear that you are having issues with the wallet.  It never synced for me and I'm not sure if it had to do with my software/hardware configuration or what.  I gave up and sold the tokens to jump into something else.  Good luck

**Comment by jhmblvd** [comment] 2017-11-12 00:19
I sent my coins to the wallet address, so how do I get them now and sell them. The fact that you can't get help or that this wallet is not working speaks very poorly about the future of this project. Who do you go to for help?

**Comment by jhmblvd** [comment] 2017-11-12 00:27
also, the address is not showing up in blockchain explorer? What's up here? Bittrex shows it went through, shows the address and when I paste that into the explorer it comes up empty. Who supports this ?

**Comment by vtorrent** [comment] 2017-11-12 02:01
Hello, the reason for "the address not showing up in blockchain" is due to the address being Stealth Address by design. Regarding Out of Sync issue, please run following command in console "addnode <node> add" for example "addnode 118.40.228.76 add"

**Comment by Jousepetion** [comment] 2017-11-12 07:32
I now get an invalid proxy address.

**Comment by jhmblvd** [comment] 2017-11-13 00:01
Add nose is to add my up address?

**Comment by jhmblvd** [comment] 2017-11-13 00:07
Also, sorry for the newbee question but where do I add the node? Where is
the console, do you mean the console (my windows command line interface) or
within the client itself? What am I adding when I add the node. I don't mean to be rude but this is just crazy, no instructions, no tutorials, just download the wallet and it fails to work? Again appreciate that it's private and the work you're doing but if there are specific steps that must be taken to get your coin then this needs to be explained so folks like myself can understand it :) Thanks for your help, not one other reply from any other source has even bothered to try and help. I'm no whale just a normal guy trying to back a project that sounded good. 

John



John Mahoney

**Comment by vtorrent** [comment] 2017-11-13 05:20
Console is located in Help dropdown menu under "Debug", please copy amd paste this command in the console window "addnode 118.40.228.76 add"

**Comment by jhmblvd** [comment] 2017-11-13 15:37
Ok, I was able to add the node. Still showing out of sync but realize it may take a while. Anything else I need to do in order to fix this?

**Comment by jhmblvd** [comment] 2017-11-13 15:39
Should the default settings under Options work? Particularly do I need to map the port 9050 or use the SOCKS proxy?

**Comment by jhmblvd** [comment] 2017-11-13 16:17
Still not syncing. I also searched the blockchain using the stealth address and it's not there??? Yet Bittrex says it's gone through. This is absolutely the hardest experience I have yet had moving a coin.

**Comment by vtorrent** [comment] 2017-11-13 16:22
You need to wait until the blockchain all sync up until you could see your current balance.

This is completely normal behavior including with Bitcoin core. 

Normally it should take few hours or more depends on connection speed.

**Comment by Jousepetion** [comment] 2017-11-13 16:23
Any possibility of getting help with my issue of not being able to access the wallet because  of "invalid proxy address."

**Comment by vtorrent** [comment] 2017-11-13 16:26
What is your current proxy setting? You could also try to remove vTorrent-HD folder and start over.

**Comment by jhmblvd** [comment] 2017-11-13 17:05
I just accepted the default values when setting up the wallet. Mine has two options Map using UPnP and Connect through SOCKS Proxy, which is the correct setting for a windows machine? I don't use a proxy.

**Comment by jhmblvd** [comment] 2017-11-14 01:15
So far no syncing. It successfully added the node but still no balance and my coin is not available to me

**Comment by Jousepetion** [comment] 2017-11-15 01:25
At this point, I'm just waiting for the new wallet so I could cut my losses with this coin. No real community to get info and tech support.

**Comment by jhmblvd** [comment] 2017-11-16 00:14
I have added nodes, tried different settings, verified the transaction with Bittrex and now I see nothing downloading and the wallet after 3 days is still out of sync. The spinner spins and it shows 19 connections but shows 0 of 160867  headers downloaded. That's a zero. You should have warned people to NOT TRANSFER coin to wallets until the wallet was ready for prime time. One of the worst experiences I've had with Alt coins, no community no support, no answers.

**Comment by Jousepetion** [comment] 2017-11-16 00:17
LOL like you, I fucked around with the settings so much can't open the wallet anymore... "invalid proxy address." message.

**Comment by vtorrent** [comment] 2017-11-16 00:29
Your client isn't properly synced. You may try to follow this video from our community member to fix the issue you are facing, https://t.co/0mCstrksRd

**Comment by jhmblvd** [comment] 2017-11-16 16:15
Not only won't it sync it won't open now, I thought I would leave it open overnight to see if it would start  to sync, instead it doesn't show up as running, there's no icon indicating it's open, no processes that I can find indicating it's running, and yet when I try to open it it says "Fatal Error vTorrent is probably Open" why would you release a product that doesn't work or run on Windows without telling people it doesn't run or work on windows? I've already viewed the above video - nope doesn't work still. Contacted Bittrex about this being a scam coin and they stated that the reason the transaction is not showing up is because your blockchain explorer is not working. Wow, don't get this at all.

**Comment by vtorrent** [comment] 2017-11-16 16:25
If you really have tried everything and still cannot get the client to sync up, you are clearly doing something wrong and sorry I will not give you anymore advice other than just wait for the new client which should be more suitable to newbie.

**Comment by slugmandrew** [comment] 2017-11-16 18:30
@jhmblvd man, I have no idea how you've managed this. The wallet runs really well for me on windows, no issues at all. Do a fresh install?

**Comment by vtorrent** [comment] 2018-01-21 15:00
v0.8.2.1 completely solved this issue

**Closed as completed by vtorrent** 2018-01-21 15:00 UTC
